name: Push to GitHub

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: download terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7
    - name: terraform init
      run: terraform init
    - name: plan
      run: terraform plan
    - name: terraform apply 
      run: terraform apply -auto-approve

    - name: Push code
      run: |
        git config --local user.email "vikrantchughimp@gmail.com"
        git config --local user.name "VikrantChugh"
        git add .
        git commit -m "Auto commit by GitHub Actions"
        git push
