name: Push to GitHub

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push code
      run: |
        git config --local user.email "vikrantchughimp@gmail.com"
        git config --local user.name "VikrantChugh"
        git add .
        git commit -m "Auto commit by GitHub Actions"
        git push
